language: node_js
node_js:
  - '13.11.0'
services: mongodb
deploy:
  provider: lambda
  function_name: "cs3219-addressbook-dev-app"
  region: "us-east-1"
  role: "arn:aws:iam::047742761070:role/cs3219-addressbook-dev-us-east-1-lambdaRole"
  runtime: "nodejs12.x"
  handler_name: "handler"
  on:
    branch: release