service: cs3219-addressbook
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: index.handler
    events: 
      - http: ANY /
      - http: ANY /{proxy+}